### PR TITLE
Add Groestlcoin support

### PR DESCRIPTION
**Pull request by gruve-p**

### CODE REVIEW

**Comment by prusnak** [comment]
The change does not look so big afterall. Can you try submitting the same pull request to upstream (BitGo/bitgo-utxo-lib) first?

**Comment by gruve-p** [comment]
https://github.com/BitGo/bitgo-utxo-lib/pull/22

**Comment by prusnak** [comment]
Thanks!

**Comment by gruve-p** [comment]
Implementation has been tested as working on Zelcore:
https://github.com/TheTrunk/bitgo-utxo-lib/pull/2

**Comment by gruve-p** [comment]
@prusnak Upstream is unlikely going to merge our PR request. Can you merge this PR, it has been tested by @TheTrunk

**Comment by prusnak** [comment]
This PR is failing tests. Plus there are no tests for added functionality. We can't merge this as is.

**Comment by szymonlesisz** [comment]
To be honest this PR is not very nice, there is too much integration in API objects, methods params and dependencies.

Generally i don't like the idea of keeping coin specific hashing libraries as a dependency (https://github.com/Groestlcoin/groestl-hash-js.git), especially when they are downloaded straight from github master branch. Note that this library is created primary for bitcoin and yet every "pure" bitcoin wallet which depends on this lib will have `groestl-hash-js` compiled because of this change.
So, first of all consider to publish this lib to npm.

Extending every network with "hashFunctions" field is also a bad idea. 
Those network objects could be (and they are) used in some parent project, after this change those objects will not be compatible anymore, for example sending `network` thru some http request will fail because you can't send "function"

Another example [this code](https://github.com/trezor/trezor-utxo-lib/blob/5d91049fd7a988382df81c8260e244ee56d57aac/src/hdnode.js#L61-L63) totally changes function logic, you are not able to use array of networks anymore

All of this could be done better if you consider to override default `base58check` which is problematic in this case.
Or maybe add this special hashing functions as a plugin, which could be enabled (and conditionally compiled) only for those who needs it.
You can get inspired by [this commit](https://github.com/trezor/trezor-utxo-lib/blob/6d09a1395d2794cefa30d469f8dad9512ad4d357/src/transaction.js#L57) where you can request every Transaction object to read/write outputs values as a string. If you don't need it you just don't have to do anything and it will work fine, like it did before.

**Comment by gruve-p** [comment]
@szymonlesisz We have addressed all the above concerns, can you reopen this Pull Request or should we submit a new Pull Request? We would love to get your feedback.

**Comment by gruve-p** [comment]
@szymonlesisz Can this be reopened so we can address your concerns?

**Comment by prusnak** [comment]
We are not interested in adding your coin into our stack at the moment. It's adding too much technological debt by introducing so much complexity.

**Comment by gruve-p** [comment]
@prusnak Thank you for the prompt reply.
I hope that changes in the future and will try again later this year.

What about if Decred gets added (saw some Pr's open for it)? We can add GRS much easier if Decred gets integrated (they are introducing the same technological debt as GRS. We can reuse their implementation so our implementation is just a few lines minus the tests)

**Comment by prusnak** [comment]
Decred is not using an uncommon hash function, it uses a pretty standard one, so your assessment about the debt is wrong.

**Pull request closed without merging**
